# Generated by Django 4.1.7 on 2023-03-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(error_messages={'unique': 'This todo already exists'}, max_length=200, unique=True),
        ),
    ]
